"""add is_indexed to file model

Revision ID: f3646a250247
Revises: 623b80d4ff95
Create Date: 2025-04-27 10:29:35.960108

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3646a250247"
down_revision: Union[str, None] = "623b80d4ff95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("is_indexed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "is_indexed")
    # ### end Alembic commands ###
